"""add ncs_lclas table

Revision ID: 3541746383a7
Revises: 94453857611b
Create Date: 2026-05-08 20:52:14.120673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3541746383a7'
down_revision: Union[str, None] = '94453857611b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncs_lclas',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code', 'degree')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ncs_lclas')
    # ### end Alembic commands ###
