"""add job_research cache and roadmap ncs_job_code

Revision ID: 418b219c27e8
Revises: 7c38e63e606e
Create Date: 2026-07-15 20:41:13.314024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '418b219c27e8'
down_revision: Union[str, None] = '7c38e63e606e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_research',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ncs_job_code', sa.String(), nullable=False),
    sa.Column('ncs_job_name', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('academic_societies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('expert_insights', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_research_ncs_job_code'), 'job_research', ['ncs_job_code'], unique=True)
    op.add_column('roadmaps', sa.Column('ncs_job_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'ncs_job_code')
    op.drop_index(op.f('ix_job_research_ncs_job_code'), table_name='job_research')
    op.drop_table('job_research')
    # ### end Alembic commands ###
