"""add milestone posts, likes, comments, user bio, roadmap featured flag

Revision ID: 4d84bfd0e863
Revises: 7d7687d888c8
Create Date: 2026-07-14 21:45:18.704724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d84bfd0e863'
down_revision: Union[str, None] = '7d7687d888c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('milestone_id')
    )
    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['milestone_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['milestone_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_like')
    )
    op.add_column('roadmaps', sa.Column('is_featured', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('roadmaps', 'is_featured')
    op.drop_table('post_likes')
    op.drop_table('post_comments')
    op.drop_table('milestone_posts')
    # ### end Alembic commands ###
