"""add_ncs_hierarchy

Revision ID: 6e4e16cd5927
Revises: 3541746383a7
Create Date: 2026-05-16 23:38:31.042403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e4e16cd5927'
down_revision: Union[str, None] = '3541746383a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncs_mclas',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('lclas_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lclas_code', 'degree'], ['ncs_lclas.code', 'ncs_lclas.degree'], ),
    sa.PrimaryKeyConstraint('code', 'degree')
    )
    op.create_table('ncs_sclas',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('mclas_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mclas_code', 'degree'], ['ncs_mclas.code', 'ncs_mclas.degree'], ),
    sa.PrimaryKeyConstraint('code', 'degree')
    )
    op.create_table('ncs_job',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('sclas_code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sclas_code', 'degree'], ['ncs_sclas.code', 'ncs_sclas.degree'], ),
    sa.PrimaryKeyConstraint('code', 'degree')
    )
    op.create_table('ncs_ability_unit',
    sa.Column('code', sa.String(length=14), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('job_code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_code', 'degree'], ['ncs_job.code', 'ncs_job.degree'], ),
    sa.PrimaryKeyConstraint('code', 'degree')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ncs_ability_unit')
    op.drop_table('ncs_job')
    op.drop_table('ncs_sclas')
    op.drop_table('ncs_mclas')
    # ### end Alembic commands ###
