"""add todo categories and items

Revision ID: 7c38e63e606e
Revises: 895f01873487
Create Date: 2026-07-15 14:55:27.675281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7c38e63e606e'
down_revision: Union[str, None] = '895f01873487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), server_default='green', nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_categories_user_id'), 'todo_categories', ['user_id'], unique=False)
    op.create_table('todo_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['todo_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_items_category_id'), 'todo_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_todo_items_due_date'), 'todo_items', ['due_date'], unique=False)
    op.create_index(op.f('ix_todo_items_user_id'), 'todo_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_items_user_id'), table_name='todo_items')
    op.drop_index(op.f('ix_todo_items_due_date'), table_name='todo_items')
    op.drop_index(op.f('ix_todo_items_category_id'), table_name='todo_items')
    op.drop_table('todo_items')
    op.drop_index(op.f('ix_todo_categories_user_id'), table_name='todo_categories')
    op.drop_table('todo_categories')
    # ### end Alembic commands ###
