"""add bean transactions and roadmap beans_awarded_at

Revision ID: 895f01873487
Revises: 4d84bfd0e863
Create Date: 2026-07-15 09:01:54.483140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '895f01873487'
down_revision: Union[str, None] = '4d84bfd0e863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bean_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('roadmap_title', sa.String(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bean_transactions_user_id'), 'bean_transactions', ['user_id'], unique=False)
    op.add_column('roadmaps', sa.Column('beans_awarded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'beans_awarded_at')
    op.drop_index(op.f('ix_bean_transactions_user_id'), table_name='bean_transactions')
    op.drop_table('bean_transactions')
    # ### end Alembic commands ###
