"""add_lclas_mclas_code_to_ncs_job

Revision ID: a2f41c40a539
Revises: 6e4e16cd5927
Create Date: 2026-05-17 14:17:02.769622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a2f41c40a539'
down_revision: Union[str, None] = '6e4e16cd5927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncs_job', sa.Column('lclas_code', sa.String(length=2), nullable=False))
    op.add_column('ncs_job', sa.Column('mclas_code', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ncs_job', 'mclas_code')
    op.drop_column('ncs_job', 'lclas_code')
    # ### end Alembic commands ###
